services:
  instagram-copy-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - 5432:5432
    volumes:
      - instagram-copy-volume:/var/lib/postgresql/data

  instagram-copy-backend:
    image: instagram-copy-backend-img:1545
    restart: always
    ports:
      - 8080:80
    depends_on:
      - instagram-copy-db
    environment:
      - DbSettings__Host=instagram-copy-db
      - DbSettings__Port=5432
      - DbSettings__Database=instagram-copy-db
      - DbSettings__Username=your_username
      - DbSettings__Password=your_password
          
volumes:
  instagram-copy-volume:
