apiVersion: apps/v1
kind: Deployment
metadata:
  name: instagram-copy-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: instagram-copy-backend
  template:
    metadata:
      labels:
        app: instagram-copy-backend
    spec:
      containers:
        - name: instagram-copy-backend-container
          image: instagram0copy0acr.azurecr.io/instagram-copy-backend:587362092eca7e4b315ca5552efc8fbfb2c159b8
          imagePullPolicy: Always
          ports:
            - containerPort: 80
