apiVersion: apps/v1
kind: Deployment
metadata:
  name: instagram-copy-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: instagram-copy-backend
  template:
    metadata:
      labels:
        app: instagram-copy-backend
    spec:
      containers:
        - name: instagram-copy-backend-container
          image: instagram0copy0acr.azurecr.io/instagram-copy-backend:587362092eca7e4b315ca5552efc8fbfb2c159b8
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:  
            - name: DbSettings__Host
              value: instagram-copy-db-service.default.svc.cluster.local
            - name: DbSettings__Port
              value: "5432"            
            - name: DbSettings__Database
              value: instagram-copy-db
            - name: DbSettings__Username
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: instagram-copy-db-username        
            - name: DbSettings__Password
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: instagram-copy-db-password